### ISSUE TITLE
[Delegation Permissions] RPC to get list of schema ids granted for delegator

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#392] opened 2022-08-29 17:11 UTC
on similar lines as #224 , we need  a Get operation

Blocked  by #224 

As a provider I should be able to get a list of schema_ids granted for a delegator via RPC call

### Acceptance Criteria.
- [ ]  Add an RPC call to get a list of schema ids granted for a delegator by a provider 
- [ ] Update runtime and node/service to add RPC to runtime.
- [ ] Tests

**Comment by wilwade** [comment] 2022-08-29 23:02
@saraswatpuneet 
Is this a duplicate of https://github.com/LibertyDSNP/frequency/issues/316

**Comment by saraswatpuneet** [comment] 2022-08-31 10:35
@wilwade  how about now, do we need an RPC call if not we can close this issue as not needed

**Comment by wilwade** [comment] 2022-08-31 11:51
@saraswatpuneet RPC call is covered by https://github.com/LibertyDSNP/frequency/issues/226 So this is a duplicate (although I like this wording better, so I'll copy it over to the other one)

**Closed** 2022-08-31 11:54 UTC
Labels: blocked
