### ISSUE TITLE
Disable all non-required features for launch

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#278] opened 2022-07-28 00:03 UTC
1. Implement feature flag functionality
2. Turn off the features that we aren't launching with.
3. Verify release functionality for only what we should launch with.

**Comment by wilwade** [comment] 2022-08-15 20:12
Duplicate of https://github.com/LibertyDSNP/frequency/issues/257

**Closed by wilwade** 2022-08-15 20:12 UTC
