### ISSUE TITLE
[Capacity] Allocate a certain amount of block space for capacity transactions

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1016] opened 2023-02-02 15:26 UTC
needs to be groomed

**Comment by p5150j** [comment] 2023-02-02 15:27
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1016?planning-poker) with Zenhub @enddynayn @johnmela @shannonwells

**Comment by enddynayn** [comment] 2023-04-12 17:43
@shannonwells nope. This is a ticket for the next phase of Capacity, where we want to allocate a certain amount of block space for Capacity transactions.

**Comment by wilwade** [comment] 2023-04-21 17:47
Duplicate of #141

**Closed by wilwade** 2023-04-21 17:47 UTC
Labels: Capacity
